theme: minima
title: Global Humanitarianism Research Academy (GHRA)
author:
  name: Leibniz Institute of European History (IEG)
  email: info@ieg-mainz.de
description: Website of the Global Humanitarianism Research Academy (GHRA)
imprint:
  url: https://github.com/ieg-dhr
  name: Imprint | Data Protection
